# MySQL Konfigürasyonu
spring.datasource.url=jdbc:postgresql://localhost:5432/runexus
spring.datasource.username=postgres
spring.datasource.password=pass


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# PostgreSQL driver ve dialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


spring.datasource.hikari.maximum-pool-size=10
spring.h2.console.enabled=false

spring.security.user.name=admin
spring.security.user.password=admin
spring.main.allow-bean-definition-overriding=true

spring.jackson.default-property-inclusion=NON_NULL
spring.main.allow-circular-references=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
